### ISSUE TITLE
Fill Tables with start data

### ISSUE THREAD

**Issue by JohnMDoll** [nss-day-cohort-60/national-parks-api#3]
The following tables should have data INSERTed:

- [x] Users - ticket #4 
- [x] Parks - ticket #9 
- [x] Amenities - ticket #10
- [x] Park_Amenities - ticket #11
- [x] Wildlife_Groups - ticket #12
- [x] Wildlife - ticket #13
- [x] Park_Wildlife - ticket #14
- [x] Natural_Attractions - ticket #15
- [x] Park_Natural_Attractions - ticket #16
- [x] Campgrounds - ticket #17
- [x] Events - ticket #18
- [x] Favorite_Types - ticket #19
- [x] Photos - ticket #20 
- -----------------added-----------------
- [x] Events_Registration - ticket #26
- [x] Blogs, Photos, Blog_Photos - ticket #27
- [x] User_Favorites - ticket #28
- [x] Camping_Reservations - ticket #29
