### ISSUE TITLE
Server Functions for Client "Park" page

### ISSUE THREAD

**Issue by JohnMDoll** [nss-day-cohort-60/national-parks-api#47]
Breaks down ticket #6 supporting needs

Client is building a park page and requires:

GET for:

- [ ] 1 park, by id - ticket #6 
- [ ] campgrounds by park_id - ticket #50 
- [ ] wildlife by park id -ticket #46
- [ ] 1 wildlife by id filtered by park id - ticket  #45
- [ ] all natural attractions by park id - ticket #48
- [ ] amenities by park id - ticket #51 
- [ ] blogs by park id - ticket #52 

Will need to display photos for wildlife, parks, and blogs
